//
// Created for coat btop theming module
//

#include "btop.h"
#include "tinted_parser.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>

// Apply theme to btop system monitor
int btop_apply_theme(const Base16Scheme *scheme) {
    if (!scheme) {
        return -1;
    }
    
    const char *home = getenv("HOME");
    if (!home) {
        fprintf(stderr, "Could not determine home directory\n");
        return -1;
    }
    
    // Create btop themes directory if it doesn't exist
    char themes_dir[1024];
    snprintf(themes_dir, sizeof(themes_dir), "%s/.config/btop/themes", home);
    
    // Create directory structure recursively
    char config_dir[1024];
    snprintf(config_dir, sizeof(config_dir), "%s/.config/btop", home);
    mkdir(config_dir, 0755);
    mkdir(themes_dir, 0755);
    
    // Generate theme path
    char theme_path[1024];
    snprintf(theme_path, sizeof(theme_path), "%s/coat.theme", themes_dir);
    
    printf("Generating btop theme: %s\n", theme_path);
    
    FILE *f = fopen(theme_path, "w");
    if (!f) {
        fprintf(stderr, "Failed to create btop theme: %s\n", theme_path);
        return -1;
    }
    
    // Write header
    fprintf(f, "# Btop theme: %s\n", scheme->name);
    fprintf(f, "# Author: %s\n", scheme->author);
    if (scheme->variant[0]) {
        fprintf(f, "# Variant: %s\n", scheme->variant);
    }
    fprintf(f, "# Generated by coat\n");
    fprintf(f, "\n");
    
    // Main background and foreground
    fprintf(f, "theme[main_bg]=\"%s\"\n", scheme->base00);
    fprintf(f, "theme[main_fg]=\"%s\"\n", scheme->base05);
    
    // Title colors
    fprintf(f, "theme[title]=\"%s\"\n", scheme->base0D);  // Blue for titles
    
    // Highlighted and selected
    fprintf(f, "theme[hi_fg]=\"%s\"\n", scheme->base0D);  // Blue
    fprintf(f, "theme[selected_bg]=\"%s\"\n", scheme->base02);
    fprintf(f, "theme[selected_fg]=\"%s\"\n", scheme->base0D);
    
    // Inactive and unfocused
    fprintf(f, "theme[inactive_fg]=\"%s\"\n", scheme->base03);
    
    // Process colors
    fprintf(f, "theme[proc_misc]=\"%s\"\n", scheme->base0C);  // Cyan
    fprintf(f, "theme[cpu_box]=\"%s\"\n", scheme->base0D);    // Blue
    fprintf(f, "theme[mem_box]=\"%s\"\n", scheme->base0B);    // Green
    fprintf(f, "theme[net_box]=\"%s\"\n", scheme->base0E);    // Magenta
    fprintf(f, "theme[proc_box]=\"%s\"\n", scheme->base0A);   // Yellow
    
    // Divider lines
    fprintf(f, "theme[div_line]=\"%s\"\n", scheme->base03);
    
    // Graph colors
    fprintf(f, "theme[graph_text]=\"%s\"\n", scheme->base05);
    fprintf(f, "theme[meter_bg]=\"%s\"\n", scheme->base01);
    
    // CPU graph colors
    fprintf(f, "theme[cpu_start]=\"%s\"\n", scheme->base0D);  // Blue
    fprintf(f, "theme[cpu_mid]=\"%s\"\n", scheme->base0C);    // Cyan
    fprintf(f, "theme[cpu_end]=\"%s\"\n", scheme->base0B);    // Green
    
    // Free memory graph
    fprintf(f, "theme[free_start]=\"%s\"\n", scheme->base0B);  // Green
    fprintf(f, "theme[free_mid]=\"%s\"\n", scheme->base0C);    // Cyan
    fprintf(f, "theme[free_end]=\"%s\"\n", scheme->base0D);    // Blue
    
    // Cached memory
    fprintf(f, "theme[cached_start]=\"%s\"\n", scheme->base0E);  // Magenta
    fprintf(f, "theme[cached_mid]=\"%s\"\n", scheme->base0A);    // Yellow
    fprintf(f, "theme[cached_end]=\"%s\"\n", scheme->base08);    // Red
    
    // Available memory
    fprintf(f, "theme[available_start]=\"%s\"\n", scheme->base0A);  // Yellow
    fprintf(f, "theme[available_mid]=\"%s\"\n", scheme->base0B);    // Green
    fprintf(f, "theme[available_end]=\"%s\"\n", scheme->base0C);    // Cyan
    
    // Used memory
    fprintf(f, "theme[used_start]=\"%s\"\n", scheme->base08);  // Red
    fprintf(f, "theme[used_mid]=\"%s\"\n", scheme->base09);    // Orange
    fprintf(f, "theme[used_end]=\"%s\"\n", scheme->base0A);    // Yellow
    
    // Download colors
    fprintf(f, "theme[download_start]=\"%s\"\n", scheme->base0B);  // Green
    fprintf(f, "theme[download_mid]=\"%s\"\n", scheme->base0C);    // Cyan
    fprintf(f, "theme[download_end]=\"%s\"\n", scheme->base0D);    // Blue
    
    // Upload colors
    fprintf(f, "theme[upload_start]=\"%s\"\n", scheme->base0E);  // Magenta
    fprintf(f, "theme[upload_mid]=\"%s\"\n", scheme->base09);    // Orange
    fprintf(f, "theme[upload_end]=\"%s\"\n", scheme->base08);    // Red
    
    // Process colors
    fprintf(f, "theme[process_start]=\"%s\"\n", scheme->base0C);  // Cyan
    fprintf(f, "theme[process_mid]=\"%s\"\n", scheme->base0D);    // Blue
    fprintf(f, "theme[process_end]=\"%s\"\n", scheme->base0E);    // Magenta
    
    // Temperature
    fprintf(f, "theme[temp_start]=\"%s\"\n", scheme->base0B);  // Green (cold)
    fprintf(f, "theme[temp_mid]=\"%s\"\n", scheme->base0A);    // Yellow (warm)
    fprintf(f, "theme[temp_end]=\"%s\"\n", scheme->base08);    // Red (hot)
    
    fclose(f);
    
    printf("Btop theme generated successfully!\n");
    printf("\nTo activate:\n");
    printf("1. Open btop\n");
    printf("2. Press ESC to open menu\n");
    printf("3. Navigate to 'Options' > 'Color theme'\n");
    printf("4. Select 'coat'\n");
    printf("\nOr set in ~/.config/btop/btop.conf:\n");
    printf("  color_theme = \"coat\"\n");
    printf("\nSee USAGE.md for more details.\n");
    
    return 0;
}
