//
// Created by amarnath on 1/19/26.
//

#include "dunst.h"
#include "tinted_parser.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>

// Helper to strip # from hex color if present
static const char* strip_hash(const char *color) {
    return (color[0] == '#') ? color + 1 : color;
}

// Generate dunst config from a Base16 scheme
static int dunst_generate_config(const Base16Scheme *scheme, const char *output_path, const FontConfig *font) {
    if (!scheme || !output_path) {
        return -1;
    }
    
    FILE *f = fopen(output_path, "w");
    if (!f) {
        fprintf(stderr, "Failed to create dunst config file: %s\n", output_path);
        return -1;
    }
    
    // Write header
    fprintf(f, "# Dunst configuration\n");
    fprintf(f, "# Generated by coat\n");
    fprintf(f, "# Theme: %s\n", scheme->name);
    fprintf(f, "# Author: %s\n", scheme->author);
    if (scheme->variant[0]) {
        fprintf(f, "# Variant: %s\n", scheme->variant);
    }
    fprintf(f, "\n");
    
    // Global settings
    fprintf(f, "[global]\n");
    fprintf(f, "    # Display\n");
    fprintf(f, "    monitor = 0\n");
    fprintf(f, "    follow = mouse\n");
    fprintf(f, "\n");
    
    fprintf(f, "    # Geometry\n");
    fprintf(f, "    width = (0, 400)\n");
    fprintf(f, "    height = 300\n");
    fprintf(f, "    origin = top-right\n");
    fprintf(f, "    offset = 10x50\n");
    fprintf(f, "    scale = 0\n");
    fprintf(f, "    notification_limit = 5\n");
    fprintf(f, "\n");
    
    fprintf(f, "    # Progress bar\n");
    fprintf(f, "    progress_bar = true\n");
    fprintf(f, "    progress_bar_height = 10\n");
    fprintf(f, "    progress_bar_frame_width = 1\n");
    fprintf(f, "    progress_bar_min_width = 150\n");
    fprintf(f, "    progress_bar_max_width = 300\n");
    fprintf(f, "\n");
    
    fprintf(f, "    # Text\n");
    if (font && font->sansserif[0]) {
        fprintf(f, "    font = %s 10\n", font->sansserif);
    } else {
        fprintf(f, "    font = sans 10\n");
    }
    fprintf(f, "    line_height = 0\n");
    fprintf(f, "    markup = full\n");
    fprintf(f, "    format = \"<b>%%s</b>\\n%%b\"\n");
    fprintf(f, "    alignment = left\n");
    fprintf(f, "    vertical_alignment = center\n");
    fprintf(f, "    show_age_threshold = 60\n");
    fprintf(f, "    ellipsize = middle\n");
    fprintf(f, "    ignore_newline = no\n");
    fprintf(f, "    stack_duplicates = true\n");
    fprintf(f, "    hide_duplicate_count = false\n");
    fprintf(f, "    show_indicators = yes\n");
    fprintf(f, "\n");
    
    fprintf(f, "    # Icons\n");
    fprintf(f, "    enable_posix_regex = true\n");
    fprintf(f, "    icon_position = off\n");
    fprintf(f, "    min_icon_size = 0\n");
    fprintf(f, "    max_icon_size = 0\n");
    fprintf(f, "\n");
    
    fprintf(f, "    # History\n");
    fprintf(f, "    sticky_history = yes\n");
    fprintf(f, "    history_length = 20\n");
    fprintf(f, "\n");
    
    fprintf(f, "    # Misc/Advanced\n");
    fprintf(f, "    browser = /usr/bin/xdg-open\n");
    fprintf(f, "    always_run_script = true\n");
    fprintf(f, "    title = Dunst\n");
    fprintf(f, "    class = Dunst\n");
    fprintf(f, "    corner_radius = 8\n");
    fprintf(f, "    ignore_dbusclose = false\n");
    fprintf(f, "    force_xinerama = false\n");
    fprintf(f, "    mouse_left_click = close_current\n");
    fprintf(f, "    mouse_middle_click = do_action, close_current\n");
    fprintf(f, "    mouse_right_click = close_all\n");
    fprintf(f, "\n");
    
    fprintf(f, "    # Frame\n");
    fprintf(f, "    frame_width = 2\n");
    fprintf(f, "    frame_color = \"#%s\"\n", strip_hash(scheme->base0D));
    fprintf(f, "    separator_color = frame\n");
    fprintf(f, "    separator_height = 2\n");
    fprintf(f, "    padding = 8\n");
    fprintf(f, "    horizontal_padding = 8\n");
    fprintf(f, "    text_icon_padding = 0\n");
    fprintf(f, "    gap_size = 4\n");
    fprintf(f, "\n");
    
    // Urgency low (info notifications)
    fprintf(f, "[urgency_low]\n");
    fprintf(f, "    background = \"#%s\"\n", strip_hash(scheme->base01));
    fprintf(f, "    foreground = \"#%s\"\n", strip_hash(scheme->base05));
    fprintf(f, "    frame_color = \"#%s\"\n", strip_hash(scheme->base0C));
    fprintf(f, "    timeout = 5\n");
    fprintf(f, "\n");
    
    // Urgency normal (standard notifications)
    fprintf(f, "[urgency_normal]\n");
    fprintf(f, "    background = \"#%s\"\n", strip_hash(scheme->base01));
    fprintf(f, "    foreground = \"#%s\"\n", strip_hash(scheme->base05));
    fprintf(f, "    frame_color = \"#%s\"\n", strip_hash(scheme->base0D));
    fprintf(f, "    timeout = 10\n");
    fprintf(f, "\n");
    
    // Urgency critical (important/error notifications)
    fprintf(f, "[urgency_critical]\n");
    fprintf(f, "    background = \"#%s\"\n", strip_hash(scheme->base08));
    fprintf(f, "    foreground = \"#%s\"\n", strip_hash(scheme->base00));
    fprintf(f, "    frame_color = \"#%s\"\n", strip_hash(scheme->base08));
    fprintf(f, "    timeout = 0\n");
    fprintf(f, "\n");
    
    fclose(f);
    return 0;
}

// Apply dunst theme
int dunst_apply_theme(const Base16Scheme *scheme, const FontConfig *font) {
    if (!scheme) {
        return -1;
    }
    
    // Get home directory
    const char *home = getenv("HOME");
    if (!home) {
        fprintf(stderr, "Could not determine home directory\n");
        return -1;
    }
    
    // Create dunst config directory
    char dunst_dir[1024];
    snprintf(dunst_dir, sizeof(dunst_dir), "%s/.config/dunst", home);
    
    // Create directory if it doesn't exist
    mkdir(dunst_dir, 0755);
    
    // Generate dunst config
    char config_path[1024];
    snprintf(config_path, sizeof(config_path), "%s/dunstrc", dunst_dir);
    
    if (dunst_generate_config(scheme, config_path, font) != 0) {
        return -1;
    }
    
    printf("  Created dunst config: %s\n", config_path);
    
    // Try to restart dunst to apply the theme
    printf("  Restarting dunst to apply theme...\n");
    int result = system("killall dunst 2>/dev/null; dunst &");
    
    if (result == 0) {
        printf("  Dunst restarted successfully!\n");
    } else {
        printf("  Note: Could not restart dunst automatically. Run 'killall dunst && dunst &' to apply.\n");
    }
    
    return 0;
}
