//
// Created by coat
//

#include "xresources.h"
#include "tinted_parser.h"
#include "yaml.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// Helper to strip # from hex color if present
static const char* strip_hash(const char *color) {
    return (color[0] == '#') ? color + 1 : color;
}

// Generate .Xresources from a Base16 scheme
static int xresources_generate_config(const Base16Scheme *scheme, const char *output_path, const FontConfig *font) {
    if (!scheme || !output_path) {
        return -1;
    }
    
    FILE *f = fopen(output_path, "w");
    if (!f) {
        fprintf(stderr, "Failed to create Xresources file: %s\n", output_path);
        return -1;
    }
    
    // Write header
    fprintf(f, "! Xresources configuration\n");
    fprintf(f, "! Generated by coat\n");
    fprintf(f, "! Theme: %s\n", scheme->name);
    fprintf(f, "! Author: %s\n", scheme->author);
    if (scheme->variant[0]) {
        fprintf(f, "! Variant: %s\n", scheme->variant);
    }
    fprintf(f, "\n");
    
    // Base16 color definitions
    fprintf(f, "! Base16 colors\n");
    fprintf(f, "#define base00 #%s\n", strip_hash(scheme->base00));
    fprintf(f, "#define base01 #%s\n", strip_hash(scheme->base01));
    fprintf(f, "#define base02 #%s\n", strip_hash(scheme->base02));
    fprintf(f, "#define base03 #%s\n", strip_hash(scheme->base03));
    fprintf(f, "#define base04 #%s\n", strip_hash(scheme->base04));
    fprintf(f, "#define base05 #%s\n", strip_hash(scheme->base05));
    fprintf(f, "#define base06 #%s\n", strip_hash(scheme->base06));
    fprintf(f, "#define base07 #%s\n", strip_hash(scheme->base07));
    fprintf(f, "#define base08 #%s\n", strip_hash(scheme->base08));
    fprintf(f, "#define base09 #%s\n", strip_hash(scheme->base09));
    fprintf(f, "#define base0A #%s\n", strip_hash(scheme->base0A));
    fprintf(f, "#define base0B #%s\n", strip_hash(scheme->base0B));
    fprintf(f, "#define base0C #%s\n", strip_hash(scheme->base0C));
    fprintf(f, "#define base0D #%s\n", strip_hash(scheme->base0D));
    fprintf(f, "#define base0E #%s\n", strip_hash(scheme->base0E));
    fprintf(f, "#define base0F #%s\n", strip_hash(scheme->base0F));
    fprintf(f, "\n");
    
    // Font settings
    if (font && font->monospace[0]) {
        fprintf(f, "! Font settings\n");
        fprintf(f, "*font: xft:%s:size=%d\n", font->monospace, font->sizes.terminal);
        fprintf(f, "*boldFont: xft:%s:bold:size=%d\n", font->monospace, font->sizes.terminal);
        fprintf(f, "*italicFont: xft:%s:italic:size=%d\n", font->monospace, font->sizes.terminal);
        fprintf(f, "*boldItalicFont: xft:%s:bold:italic:size=%d\n", font->monospace, font->sizes.terminal);
        fprintf(f, "\n");
    }
    
    // URxvt settings
    fprintf(f, "! URxvt settings\n");
    fprintf(f, "URxvt.background: base00\n");
    fprintf(f, "URxvt.foreground: base05\n");
    fprintf(f, "URxvt.cursorColor: base05\n");
    fprintf(f, "\n");
    fprintf(f, "! Black\n");
    fprintf(f, "URxvt.color0: base00\n");
    fprintf(f, "URxvt.color8: base03\n");
    fprintf(f, "\n");
    fprintf(f, "! Red\n");
    fprintf(f, "URxvt.color1: base08\n");
    fprintf(f, "URxvt.color9: base08\n");
    fprintf(f, "\n");
    fprintf(f, "! Green\n");
    fprintf(f, "URxvt.color2: base0B\n");
    fprintf(f, "URxvt.color10: base0B\n");
    fprintf(f, "\n");
    fprintf(f, "! Yellow\n");
    fprintf(f, "URxvt.color3: base0A\n");
    fprintf(f, "URxvt.color11: base0A\n");
    fprintf(f, "\n");
    fprintf(f, "! Blue\n");
    fprintf(f, "URxvt.color4: base0D\n");
    fprintf(f, "URxvt.color12: base0D\n");
    fprintf(f, "\n");
    fprintf(f, "! Magenta\n");
    fprintf(f, "URxvt.color5: base0E\n");
    fprintf(f, "URxvt.color13: base0E\n");
    fprintf(f, "\n");
    fprintf(f, "! Cyan\n");
    fprintf(f, "URxvt.color6: base0C\n");
    fprintf(f, "URxvt.color14: base0C\n");
    fprintf(f, "\n");
    fprintf(f, "! White\n");
    fprintf(f, "URxvt.color7: base05\n");
    fprintf(f, "URxvt.color15: base07\n");
    fprintf(f, "\n");
    
    // XTerm settings
    fprintf(f, "! XTerm settings\n");
    fprintf(f, "XTerm*background: base00\n");
    fprintf(f, "XTerm*foreground: base05\n");
    fprintf(f, "XTerm*cursorColor: base05\n");
    fprintf(f, "\n");
    fprintf(f, "! Black\n");
    fprintf(f, "XTerm*color0: base00\n");
    fprintf(f, "XTerm*color8: base03\n");
    fprintf(f, "\n");
    fprintf(f, "! Red\n");
    fprintf(f, "XTerm*color1: base08\n");
    fprintf(f, "XTerm*color9: base08\n");
    fprintf(f, "\n");
    fprintf(f, "! Green\n");
    fprintf(f, "XTerm*color2: base0B\n");
    fprintf(f, "XTerm*color10: base0B\n");
    fprintf(f, "\n");
    fprintf(f, "! Yellow\n");
    fprintf(f, "XTerm*color3: base0A\n");
    fprintf(f, "XTerm*color11: base0A\n");
    fprintf(f, "\n");
    fprintf(f, "! Blue\n");
    fprintf(f, "XTerm*color4: base0D\n");
    fprintf(f, "XTerm*color12: base0D\n");
    fprintf(f, "\n");
    fprintf(f, "! Magenta\n");
    fprintf(f, "XTerm*color5: base0E\n");
    fprintf(f, "XTerm*color13: base0E\n");
    fprintf(f, "\n");
    fprintf(f, "! Cyan\n");
    fprintf(f, "XTerm*color6: base0C\n");
    fprintf(f, "XTerm*color14: base0C\n");
    fprintf(f, "\n");
    fprintf(f, "! White\n");
    fprintf(f, "XTerm*color7: base05\n");
    fprintf(f, "XTerm*color15: base07\n");
    fprintf(f, "\n");
    
    // Generic X11 color settings
    fprintf(f, "! Generic X11 colors\n");
    fprintf(f, "*.background: base00\n");
    fprintf(f, "*.foreground: base05\n");
    fprintf(f, "*.cursorColor: base05\n");
    fprintf(f, "\n");
    fprintf(f, "*.color0: base00\n");
    fprintf(f, "*.color1: base08\n");
    fprintf(f, "*.color2: base0B\n");
    fprintf(f, "*.color3: base0A\n");
    fprintf(f, "*.color4: base0D\n");
    fprintf(f, "*.color5: base0E\n");
    fprintf(f, "*.color6: base0C\n");
    fprintf(f, "*.color7: base05\n");
    fprintf(f, "*.color8: base03\n");
    fprintf(f, "*.color9: base08\n");
    fprintf(f, "*.color10: base0B\n");
    fprintf(f, "*.color11: base0A\n");
    fprintf(f, "*.color12: base0D\n");
    fprintf(f, "*.color13: base0E\n");
    fprintf(f, "*.color14: base0C\n");
    fprintf(f, "*.color15: base07\n");
    fprintf(f, "\n");
    
    // Rofi color overrides (if user wants them)
    fprintf(f, "! Rofi (optional, rofi module is better)\n");
    fprintf(f, "rofi.color-window: base00, base00, base0D\n");
    fprintf(f, "rofi.color-normal: base00, base05, base00, base0D, base00\n");
    fprintf(f, "rofi.color-active: base00, base0D, base00, base0D, base00\n");
    fprintf(f, "rofi.color-urgent: base00, base08, base00, base08, base00\n");
    fprintf(f, "\n");
    
    fclose(f);
    return 0;
}

// Apply Xresources theme
int xresources_apply_theme(const Base16Scheme *scheme, const FontConfig *font) {
    if (!scheme) {
        return -1;
    }
    
    // Get home directory
    const char *home = getenv("HOME");
    if (!home) {
        fprintf(stderr, "Could not determine home directory\n");
        return -1;
    }
    
    // Generate .Xresources
    char xresources_path[1024];
    snprintf(xresources_path, sizeof(xresources_path), "%s/.Xresources", home);
    
    if (xresources_generate_config(scheme, xresources_path, font) != 0) {
        return -1;
    }
    
    printf("  Created Xresources: %s\n", xresources_path);
    
    // Try to reload Xresources with xrdb
    printf("  Reloading X resources...\n");
    char cmd[2048];
    snprintf(cmd, sizeof(cmd), "xrdb -merge %s 2>/dev/null", xresources_path);
    int result = system(cmd);
    
    if (result == 0) {
        printf("  ✓ X resources reloaded!\n");
    } else {
        printf("  Note: Could not reload automatically. Run 'xrdb -merge ~/.Xresources' to apply.\n");
    }
    
    printf("\n");
    printf("  To make permanent, add to your X session startup:\n");
    printf("    xrdb -merge ~/.Xresources\n");
    printf("\n");
    printf("  Or add to ~/.xinitrc or ~/.xprofile\n");
    
    return 0;
}
